services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=file_upload_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=letsbuildourownsecretkey
      - JWT_EXPIRES_IN=1d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_FILE_SIZE=10737418240  # 10GB
      - UPLOAD_PATH=./uploads
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network
    command: >
      sh -c "npm run db:migrate && npm run db:seed && npm start"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file_upload_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge